### PR TITLE
Home Assistant Add-on 

### PR DESCRIPTION
**Pull request by dominikandreas**
This PR adds home assistant add-on support. It is functional, but still a work in progress.

Adresses https://github.com/DennisOSRM/hms-mqtt-publisher/issues/17

Todo:
- update URLs in repository.json and config.yaml
- publish data with home assistant discovery support (separate PR for this?)
- get mqtt user, pw via bashio
- ? (Happy to accept feedback)

### CODE REVIEW

**Comment by DennisOSRM** [comment]
The pull request looks great. Is there a chance we can add a test or two to verify we don't break it by accident with future changes?

**Comment by dominikandreas** [comment]
Do you have anything in particular in mind? I'm not sure how to do automatic testing with home assistant add-ons. As long as the rust application runs in the docker image which is referenced in the Dockerfile of the addon, the addon should work as well (given non breaking changes in the CLI). Also, the addon Dockerfile references a specific version of the docker image from this repo, so even with breaking changes in the rust code, the addon keeps working until we manually upgrade it.

I suggest whoever makes changes to the add-on does some manual testing first to ensure everything works as expected. Maybe long term we can also come up with some means of automatic testing. For this we would need:
- a docker service emulating a HMS
- a docker service running an mqtt server
- a docker service running some tests and validates mqtt messages against some predefined schema
Such a test framework would of course also be useful for testing the rest of the codebase

**Comment by DennisOSRM** [comment]
That makes sense. I'll add an issue into the backlog that we add testing. In the meantime we can move ahead here and merge the PR. Once again, great work. Thanks so much.

**Comment by dominikandreas** [comment]
As mentioned, there are still some other todos. But I  can also address them in a separate PR

**Pull request merged**
