### PR TITLE
Fix oder of magnitude reported for current in HA plugin

### LINKED ISSUE #85: PV x current factor 10 too high
The current [A] for Pv x provided by MQTT in HA is factor 10 too high, e.g. 80A instead of 8A.
Please let us know whether it will be corrected in future updates.

### PR DESCRIPTION
**Pull request by DennisOSRM**
- [x] run `cargo clippy` and fix all issues
- [x] run `cargo fmt` to format all source files

---

fixes #85

### CODE REVIEW

**Comment by dominikandreas** [comment]
I think the simple MQTT publish service has the same issue: https://github.com/DennisOSRM/hms-mqtt-publisher/blob/main/hms2mqtt/src/simple_mqtt.rs#L43
Maybe we should fix it in the same PR as well.

**Comment by DennisOSRM** [comment]
This seems to be the correct order of magnitude. Or am I seeing this wrong?

**Comment by dominikandreas** [comment]
Oh, yes my mistake. Documentation in https://github.com/DennisOSRM/hms-mqtt-publisher/blob/main/hms2mqtt/src/protos/RealData.proto#L29 is wrong then

**Comment by dominikandreas** [comment]
Once the new release is there I will update the home assistant addon. Thanks for the fix

**Comment by DennisOSRM** [comment]
Oh, good catch! Will amend the PR later today and put out a release in the evening.

**Pull request merged**
